version: 2.1

jobs:
  docs:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: make html

workflows:
  docs:
    jobs:
      - docs