solver_module
logical solver_module::initialized
Referenced by solver_init, solver_solvemat.
integer(kind=ikind) solver_module::itmea
Referenced by solver_solvemat.
integer(kind=ikind) solver_module::itmin
Referenced by solver_solvemat.
integer(kind=ikind) solver_module::itmax
Referenced by solver_solvemat.
integer(kind=ikind) solver_module::ittot
Referenced by solver_solvemat.
integer(kind=ikind) solver_module::itcal
Referenced by solver_solvemat.
integer(kind=ikind) solver_module::itnconv
Referenced by solver_solvemat.
real(kind=rkind) solver_module::reps
Referenced by solver_init, solver_sip.
real(kind=rkind) solver_module::alpha
Referenced by solver_init, solver_sip.
integer(kind=ikind) solver_module::maxit
Referenced by solver_init, solver_sip.
real(kind=rkind), dimension(:,:), allocatable solver_module::residual
Referenced by solver_free, solver_init, solver_solvemat.
real(kind=rkind), dimension(:,:,:), allocatable solver_module::work
Referenced by solver_free, solver_init, solver_solvemat.
subroutine, public solver_module::solver_init(nx, ny, par)
References alpha, xmpi_module::halt_program, initialized, maxit, reps, residual, paramsconst::solver_sipp, paramsconst::solver_tridiagg, work.
Referenced by solver_solvemat.
subroutine, public solver_module::solver_free
References residual, work.
subroutine, public solver_module::solver_solvemat(amat, rhs, x, nx, ny, par)
References initialized, itcal, itmax, itmea, itmin, itnconv, ittot, residual, solver_init, solver_sip, paramsconst::solver_sipp, solver_tridiag, paramsconst::solver_tridiagg, work.
Referenced by nonh_module::nonh_1lay_cor, nonh_module::nonh_2lay_cor_2dv, nonh_module::nonh_2lay_cor_3d.
subroutine, public solver_module::solver_tridiag(amat, rhs, x, cmat, nx, ny, fixshallow)
Referenced by groundwaterflow::gw_solver, solver_solvemat.
subroutine, public solver_module::solver_sip(amat, rhs, x, res, cmat, it, nx, ny)
References alpha, maxit, reps, xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop.
Referenced by groundwaterflow::gw_solver, solver_solvemat.