waveparams
subroutine waveparams::makebcf(par, s, wp)
Creates energy and flux boundary condition files (*.bcf).
par struct with values from params.txt s struct with grid information wp struct with wave information void Todoclean up
References build_boundw, build_etdir, build_jonswap, readkey_module::readkey_dbl, swanreader, vardensreader, xmpi_module::xmaster.
subroutine waveparams::build_jonswap(par, s, wp, fname)
References frange, jonswapgk, readkey_module::readkey, readkey_module::readkey_dbl, tpdcalc, xmpi_module::xmaster.
Referenced by makebcf.
subroutine waveparams::swanreader(par, s, wp, fname)
References math_tools::flipa, math_tools::flipv, frange, xmpi_module::halt_program, readkey_module::readkey_dbl, tpdcalc, xmpi_module::xmaster.
Referenced by makebcf.
subroutine waveparams::vardensreader(par, s, wp, fname)
References frange, tpdcalc, xmpi_module::xmaster.
Referenced by makebcf.
subroutine waveparams::build_etdir(par, s, wp, Ebcfname)
References math_tools::flipiv, frange, math_tools::hilbert, init_seed, interp::linear_interp, math_tools::random, xmpi_module::xmaster.
Referenced by makebcf.
subroutine waveparams::build_boundw(par, s, wp, qbcfname)
References bc_disper, math_tools::flipiv, xmpi_module::xmaster.
Referenced by makebcf.
subroutine waveparams::jonswapgk(x, gam, y)
Referenced by build_jonswap.
subroutine waveparams::frange(par, Sf, firstp, lastp, findlineout)
Referenced by build_etdir, build_jonswap, swanreader, vardensreader.
subroutine waveparams::tpdcalc(Sf, f, Trep, trepfac, switch)
Referenced by build_jonswap, swanreader, vardensreader.
subroutine waveparams::bc_disper(k1, w1, m, h, g)
Referenced by build_boundw.
subroutine waveparams::init_seed
References math_tools::random.
Referenced by build_etdir.