flow_secondorder_module
real(kind=rkind), dimension(:,:), allocatable flow_secondorder_module::wrk1
Referenced by flow_secondorder_advuv, flow_secondorder_advw, flow_secondorder_con, flow_secondorder_init.
real(kind=rkind), dimension(:,:), allocatable flow_secondorder_module::wrk2
Referenced by flow_secondorder_advuv, flow_secondorder_advw, flow_secondorder_con, flow_secondorder_init.
logical flow_secondorder_module::initialized
Referenced by flow_secondorder_advuv, flow_secondorder_advw, flow_secondorder_con, flow_secondorder_init, nonh_module::nonh_1lay_pred.
subroutine flow_secondorder_module::flow_secondorder_init(s)
References initialized, wrk1, wrk2.
Referenced by flow_secondorder_advuv, flow_secondorder_advw, flow_secondorder_con.
subroutine, public flow_secondorder_module::flow_secondorder_advuv(s, par, uu_old, vv_old)
References flow_secondorder_init, initialized, minmod, wrk1, wrk2.
Referenced by flow_timestep_module::flow.
subroutine, public flow_secondorder_module::flow_secondorder_advw(s, par, w, w_old, mskZ)
References flow_secondorder_init, initialized, minmod, wrk1, wrk2, xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop.
Referenced by nonh_module::nonh_1lay_pred, nonh_module::nonh_2lay_pred_2dv, nonh_module::nonh_2lay_pred_3d.
subroutine, public flow_secondorder_module::flow_secondorder_con(s, par, zs_old)
References flow_secondorder_init, initialized, minmod, wrk1, wrk2.
subroutine, public flow_secondorder_module::flow_secondorder_huhv(s, par)
References minmod, xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop.
Referenced by flow_timestep_module::flow.
real(kind=rkind) pure function, public flow_secondorder_module::minmod(delta1, delta2)
Referenced by flow_secondorder_advuv, flow_secondorder_advw, flow_secondorder_con, flow_secondorder_huhv.