nonh_module
logical nonh_module::initialized
Referenced by nonh_1lay_cor, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::wcoef
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_2lay_pred_3d, nonh_init, nonh_init_wcoef.
real (kind=rkind), dimension(:,:), allocatable nonh_module::dp
Referenced by nonh_1lay_cor, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::wm
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_2lay_pred_3d, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::wm_old
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_2lay_pred_3d, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::wm0
Referenced by nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::du0
Referenced by nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_2lay_pred_3d, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::dv0
Referenced by nonh_2lay_cor_3d, nonh_2lay_pred_3d, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::omega
Referenced by nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_2lay_pred_3d, nonh_init.
real (kind=rkind), dimension(:,:,:), allocatable nonh_module::au
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_2lay_pred_3d, nonh_init.
real (kind=rkind), dimension(:,:,:), allocatable nonh_module::av
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_2lay_cor_3d, nonh_2lay_pred_3d, nonh_init.
real (kind=rkind), dimension(:,:,:), allocatable nonh_module::adu
Referenced by nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_2lay_pred_3d, nonh_init.
real (kind=rkind), dimension(:,:,:), allocatable nonh_module::adv
Referenced by nonh_2lay_cor_3d, nonh_2lay_pred_3d, nonh_init.
real (kind=rkind), dimension(:,:,:), allocatable nonh_module::mat
Referenced by nonh_1lay_cor, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::rhs
Referenced by nonh_1lay_cor, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_init.
real (kind=rkind), dimension(:,:,:), allocatable nonh_module::aws
Referenced by nonh_1lay_cor, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_2lay_pred_3d, nonh_init.
real (kind=rkind), dimension(:,:,:), allocatable nonh_module::awb
Referenced by nonh_1lay_cor, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::aur
Referenced by nonh_1lay_cor, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::avr
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::awbr
Referenced by nonh_1lay_cor, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::awsr
Referenced by nonh_1lay_cor, nonh_init.
real (kind=rkind), dimension(:,:), allocatable nonh_module::zsu
Referenced by nonh_1lay_cor, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_init, zuzv.
real (kind=rkind), dimension(:,:), allocatable nonh_module::zsv
Referenced by nonh_1lay_cor, nonh_2lay_cor_3d, nonh_init, zuzv.
real (kind=rkind), dimension(:,:), allocatable nonh_module::zbu
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_break, nonh_init, nonh_masks, zuzv.
real (kind=rkind), dimension(:,:), allocatable nonh_module::zbv
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_2lay_cor_3d, nonh_break, nonh_init, nonh_masks, zuzv.
real (kind=rkind), dimension(:), allocatable nonh_module::dxz
Referenced by nonh_1lay_cor, nonh_init.
real (kind=rkind), dimension(:), allocatable nonh_module::dyz
Referenced by nonh_1lay_cor, nonh_init.
real (kind=rkind), dimension(:), allocatable nonh_module::dxu
Referenced by nonh_1lay_pred, nonh_init.
real (kind=rkind), dimension(:), allocatable nonh_module::dyv
Referenced by nonh_1lay_pred, nonh_init.
real (kind=rkind), dimension(:), allocatable nonh_module::ddxz
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_init.
real (kind=rkind), dimension(:), allocatable nonh_module::ddyz
Referenced by nonh_1lay_cor, nonh_init.
real (kind=rkind), dimension(:), allocatable nonh_module::ddxu
Referenced by nonh_1lay_pred, nonh_init.
real (kind=rkind), dimension(:), allocatable nonh_module::ddyv
Referenced by nonh_1lay_pred, nonh_init.
integer(kind=ikind), dimension(:,:), allocatable nonh_module::nonhu
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_2lay_pred_3d, nonh_break, nonh_init, nonh_masks.
integer(kind=ikind), dimension(:,:), allocatable nonh_module::nonhv
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_2lay_cor_3d, nonh_2lay_pred_3d, nonh_break, nonh_init, nonh_masks.
integer(kind=ikind), dimension(:,:), allocatable nonh_module::nonhz
Referenced by nonh_1lay_cor, nonh_1lay_pred, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_2lay_pred_3d, nonh_break, nonh_init, nonh_masks.
real (kind=rkind), dimension(:,:), allocatable nonh_module::lbreakcond
Referenced by nonh_1lay_pred, nonh_init, nonh_masks.
subroutine, public nonh_module::nonh_cor(s, par, ipredcor, uu0, vv0)
References nonh_1lay_cor, nonh_1lay_pred, nonh_2lay_cor_2dv, nonh_2lay_cor_3d, nonh_2lay_pred_2dv, nonh_2lay_pred_3d.
Referenced by flow_timestep_module::flow.
subroutine, public nonh_module::nonh_init(s, par)
References adu, adv, au, aur, av, avr, awb, awbr, aws, awsr, ddxu, ddxz, ddyv, ddyz, dp, du0, dv0, dxu, dxz, dyv, dyz, initialized, lbreakcond, mat, nonh_init_wcoef, nonhu, nonhv, nonhz, omega, rhs, wcoef, wm, wm0, wm_old, zbu, zbv, zsu, zsv, zuzv.
Referenced by libxbeach_module::init, nonh_1lay_cor, nonh_1lay_pred.
subroutine nonh_module::nonh_1lay_cor(s, par)
References au, aur, av, avr, awb, awbr, aws, awsr, ddxz, ddyz, dp, dxz, dyz, initialized, mat, nonh_init, nonhu, nonhv, nonhz, rhs, solver_module::solver_solvemat, wcoef, wm, wm_old, xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop, zbu, zbv, zsu, zsv, zuzv.
Referenced by nonh_cor.
subroutine nonh_module::nonh_1lay_pred(s, par)
References au, av, avr, ddxu, ddxz, ddyv, dxu, dyv, flow_secondorder_module::flow_secondorder_advw, flow_secondorder_module::initialized, lbreakcond, nonh_init, nonhu, nonhv, nonhz, wcoef, wm, wm_old, zbu, zbv.
Referenced by nonh_cor.
subroutine nonh_module::nonh_2lay_cor_2dv(s, par)
References adu, au, aws, dp, du0, mat, nonhz, omega, rhs, solver_module::solver_solvemat, wcoef, wm, wm0, wm_old, xmpi_module::xmpi_isbot, xmpi_module::xmpi_istop, zbu, zsu.
Referenced by nonh_cor.
subroutine nonh_module::nonh_2lay_pred_2dv(s, par, uu0)
References adu, au, aws, du0, flow_secondorder_module::flow_secondorder_advw, nonh_break, nonhu, nonhz, omega, wcoef, wm, wm0, wm_old, zuzv.
Referenced by nonh_cor.
subroutine nonh_module::nonh_2lay_cor_3d(s, par)
References adu, adv, au, av, aws, dp, du0, dv0, mat, nonhu, nonhv, nonhz, omega, rhs, solver_module::solver_solvemat, wcoef, wm, wm0, wm_old, xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop, zbu, zbv, zsu, zsv.
Referenced by nonh_cor.
subroutine nonh_module::nonh_2lay_pred_3d(s, par, uu0, vv0)
References adu, adv, au, av, aws, du0, dv0, flow_secondorder_module::flow_secondorder_advw, nonh_break, nonhu, nonhv, nonhz, omega, wcoef, wm, wm_old, zuzv.
Referenced by nonh_cor.
subroutine nonh_module::nonh_break(s, par)
References nonhu, nonhv, nonhz, zbu, zbv.
Referenced by nonh_2lay_pred_2dv, nonh_2lay_pred_3d.
subroutine nonh_module::nonh_masks(s, par)
References lbreakcond, nonhu, nonhv, nonhz, zbu, zbv.
subroutine, public nonh_module::nonh_init_wcoef(s, par)
References disper, wave_functions_module::dispersion, wcoef.
Referenced by nonh_init, boundaryconditions::wave_bc.
subroutine nonh_module::zuzv(s)
References xmpi_module::xmpi_isbot, zbu, zbv, zsu, zsv.
Referenced by nonh_1lay_cor, nonh_2lay_pred_2dv, nonh_2lay_pred_3d, nonh_init.
real(kind=rkind) function nonh_module::disper(w, d, g, pi2, accuracy)
Referenced by nonh_init_wcoef.