filefunctions
integer function filefunctions::create_new_fid()
References create_new_fid_generic, xmpi_module::halt_program.
Referenced by check_file_length_1d, check_file_length_2d, check_file_length_3d, checkbcfilelength, readkey_module::count_lines, ncoutput_module::fortoutput_init, spectral_wave_bc_module::generate_admin_files, spectral_wave_bc_module::generate_ebcf, spectral_wave_bc_module::generate_nhtimeseries_file, spectral_wave_bc_module::generate_qbcf, wave_boundary_main_module::initialise_wave_spectrum_parameters, wave_boundary_update_module::read_jonswap_file, spectral_wave_bc_module::read_jonswap_file, wave_boundary_update_module::read_spectrum_input, spectral_wave_bc_module::read_spectrum_input, wave_boundary_update_module::read_swan_file, spectral_wave_bc_module::read_swan_file, spectral_wave_bc_module::read_vardens_file, wave_boundary_update_module::read_vardens_file, spectral_wave_bc_module::set_stationary_spectrum, initialize_module::setbathy_init, ship_module::ship_init, spectral_wave_bc_module::spectral_wave_bc, initialize_module::spectral_wave_init, vegetation_module::veggie_init.
subroutine filefunctions::check_file_exist(filename, exist, forceclose)
References check_file_exist_generic.
Referenced by params::all_input, checkbcfilelength, vegetation_module::veggie_init.
subroutine filefunctions::check_file_length_1d(fname, d1)
References create_new_fid, xmpi_module::halt_program, xmpi_module::xmaster.
subroutine filefunctions::check_file_length_2d(fname, d1, d2)
References create_new_fid, xmpi_module::halt_program, xmpi_module::xmaster.
subroutine filefunctions::check_file_length_3d(fname, d1, d2, d3)
References create_new_fid, xmpi_module::halt_program, xmpi_module::xmaster.
subroutine filefunctions::checkbcfilelength(tstop, instat, filename, filetype, nonh)
References check_file_exist, create_new_fid, xmpi_module::halt_program, logging_module::report_file_read_error, xmpi_module::xmaster.
Referenced by params::all_input.
integer function filefunctions::get_file_length(filename)
References check_file_exist_generic.
Referenced by params::all_input.
subroutine filefunctions::check_file_exist_generic(filename, error)
Referenced by check_file_exist, get_file_length.
integer function filefunctions::create_new_fid_generic()
Referenced by create_new_fid.