libxbeach_module
type(parameters) libxbeach_module::par
Referenced by xbeach_bmi::get_current_time, xbeach_bmi::get_end_time, xbeach_bmi::update.
type(timepars) libxbeach_module::tpar
Referenced by executestep, init, outputext, introspection_module::setdoubleparameter_c.
type(spacepars), pointer libxbeach_module::s
Referenced by executestep, introspection_module::get0ddoublearray_c, introspection_module::get0ddoublearray_fortran, introspection_module::get0dintarray_c, introspection_module::get0dintarray_fortran, introspection_module::get1ddoublearray_c, introspection_module::get1ddoublearray_fortran, introspection_module::get1dintarray_c, introspection_module::get1dintarray_fortran, introspection_module::get2ddoublearray_c, introspection_module::get2ddoublearray_fortran, introspection_module::get2dintarray_c, introspection_module::get2dintarray_fortran, introspection_module::get3ddoublearray_c, introspection_module::get3ddoublearray_fortran, introspection_module::get4ddoublearray_c, introspection_module::get4ddoublearray_fortran, xbeach_bmi::get_var_rank, xbeach_bmi::get_var_type, introspection_module::getarray, introspection_module::getarraydimsize_c, introspection_module::getarrayname_c, introspection_module::getarrayrank_c, introspection_module::getarraytype_c, init, outputext, introspection_module::set0ddoublearray_c, introspection_module::set0ddoublearray_fortran, introspection_module::set0dintarray_c, introspection_module::set0dintarray_fortran, introspection_module::set1ddoublearray_c, introspection_module::set1ddoublearray_fortran, introspection_module::set1dintarray_c, introspection_module::set1dintarray_fortran, introspection_module::set2ddoublearray_c, introspection_module::set2ddoublearray_fortran, introspection_module::set2dintarray_c, introspection_module::set2dintarray_fortran, introspection_module::set3ddoublearray_c, introspection_module::set3ddoublearray_fortran, introspection_module::set4ddoublearray_c, introspection_module::set4ddoublearray_fortran.
type(spacepars), target libxbeach_module::sglobal
Referenced by executestep, init, outputext.
type(ship), dimension(:), pointer libxbeach_module::sh
Referenced by executestep, init.
type(veggie), dimension(:), pointer libxbeach_module::veg
Referenced by executestep, init.
integer libxbeach_module::n
Referenced by executestep, final, init.
integer libxbeach_module::it
Referenced by executestep, init.
integer libxbeach_module::error
Referenced by executestep, init, outputext.
real*8 libxbeach_module::tbegin
Referenced by final, init.
integer(c_int) function libxbeach_module::init()
References params::all_input, beachwizard_module::bwinit, initialize_module::discharge_init, initialize_module::drifter_init, error, initialize_module::flow_init, initialize_module::grid_bathy, groundwaterflow::gw_init, it, means_module::means_init, n, nonh_module::nonh_init, output_module::output, output_module::output_init, params::params_inio, spaceparams::ranges_init, readtide_module::readtide, readwind_module::readwind, s, initialize_module::sed_init, initialize_module::setbathy_init, sglobal, sh, ship_module::ship_init, spaceparams::space_alloc_arrays_dummies, spaceparams::space_alloc_scalars, logging_module::start_logfiles, tbegin, timestep_module::timestep_init, tpar, veg, vegetation_module::veggie_init, initialize_module::wave_init, logging_module::writelog_startup, xmpi_module::xmaster, xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop, xmpi_module::xmpi_orank, xmpi_module::xmpi_pcol, xmpi_module::xmpi_prow, xmpi_module::xmpi_rank, xmpi_module::xomaster.
Referenced by xbeach_bmi::initialize, libxbeach_dynamic::xbeach_init.
integer(c_int) function libxbeach_module::outputext()
References error, output_module::output, output_module::output_error, s, sglobal, tpar.
Referenced by libxbeach_dynamic::xbeach_outputext.
integer(c_int) function libxbeach_module::executestep(dt)
References beachwizard_module::assim, beachwizard_module::assim_update, morphevolution::bed_update, wetcells_module::compute_wetcells, drifter_module::drifter, error, loopcounters_module::execute_counter, flow_timestep_module::flow, boundaryconditions::flow_bc, groundwaterflow::gw_bc, groundwaterflow::gwflow, it, n, timestep_module::outputtimes_update, s, morphevolution::setbathy_update, sglobal, sh, ship_module::shipwave, timestep_module::timestep, tpar, morphevolution::transus, veg, vegetation_module::vegatt, wave_timestep_module::wave, boundaryconditions::wave_bc, xmpi_module::xcompute.
Referenced by xbeach_bmi::update, libxbeach_dynamic::xbeach_executestep.
integer(c_int) function libxbeach_module::final()
References n, tbegin, logging_module::writelog_finalize.
Referenced by xbeach_bmi::finalize, libxbeach_dynamic::xbeach_finalize.
subroutine libxbeach_module::getversion(version)