output_module
subroutine output_module::output_init(sglobal, slocal, par, tpar)
References ncoutput_module::fortoutput_init, paramsconst::outputformat_debug, paramsconst::outputformat_fortran, paramsconst::outputformat_netcdf, ncoutput_module::points_output_init.
Referenced by libxbeach_module::init.
subroutine output_module::output(sglobal, s, par, tpar, update)
References log_progress, means_module::makeaverage, ncoutput_module::ncoutput, timestep_module::outputtimes_update.
Referenced by libxbeach_module::init, libxbeach_module::outputext.
subroutine output_module::output_error(s, sglobal, par, tpar)
References xmpi_module::halt_program.
Referenced by libxbeach_module::outputext.
subroutine output_module::log_progress(par)
Referenced by output.