interp
pure subroutine interp::linear_interp_2d(X, nx, Y, ny, Z, xx, yy, zz, method, exception)
Referenced by wave_boundary_update_module::interpolate_spectrum.
pure subroutine interp::linear_interp(x, y, n, xx, yy, indint)
References binary_search.
Referenced by waveparams::build_etdir, wave_boundary_main_module::create_incident_waves_surfbeat, boundaryconditions::discharge_boundary_h, boundaryconditions::discharge_boundary_v, boundaryconditions::flow_bc, initialize_module::flow_init, wave_boundary_update_module::generate_ebcf, spectral_wave_bc_module::generate_ebcf, wave_boundary_update_module::generate_qbcf, spectral_wave_bc_module::generate_qbcf, spectral_wave_bc_module::generate_wave_train_properties_per_offshore_point, wave_boundary_update_module::generate_wave_train_properties_per_offshore_point, spectral_wave_bc_module::generate_wave_train_variance, wave_boundary_update_module::generate_wave_train_variance, spectral_wave_bc_module::generate_wavetrain_components, wave_boundary_update_module::generate_wavetrain_components, morphevolution::hybrid, spectral_wave_bc_module::interpolate_spectrum, wave_boundary_update_module::interpolate_spectrum, initialize_module::setbathy_init, morphevolution::setbathy_update, ship_module::shipwave, trapezoidal_cyclic, boundaryconditions::wave_bc, wave_instationary_module::wave_instationary.
pure subroutine interp::binary_search(xx, n, x, j)
Referenced by linear_interp.
subroutine interp::mkmap(code, x1, y1, m1, n1, x2, y2, n2, xs, ys, nrx, nry, iflag, nrin, w, iref, iprint, covered, xymiss)
References bilin5, hunt, ipon, sort.
Referenced by ship_module::shipwave.
subroutine interp::mkmap_step(x1, y1, m1, n1, alfaz, dsu, dnv, x2, y2, n2, w, iref)
subroutine interp::grmap(f1, n1, f2, n2, iref, w, np, iprint)
Referenced by ship_module::shipwave.
subroutine interp::grmap2(f1, cellsz1i, n1, f2, cellsz2, n2, iref, w, np)
Referenced by ship_module::shipwave.
subroutine interp::ipon(xq, yq, n, xp, yp, inout)
Referenced by mkmap.
subroutine interp::hunt(xx, n, x, jlo)
Referenced by mkmap.
subroutine interp::indexx(n, arrin, indx)
Referenced by sort.
subroutine interp::bilin5(xa, ya, x0, y0, w, ier)
Referenced by mkmap.
subroutine interp::sort(n, ra, wksp, iwksp)
References indexx.
Referenced by mkmap.
subroutine interp::trapezoidal(x, y, n, x1_in, x2_in, integ)
subroutine interp::trapezoidal_cyclic(x, y, n, xcycle, x1, x2, integ)
References interp_in_cyclic_function, linear_interp.
Referenced by interp_using_trapez_rule.
subroutine interp::interp_using_trapez_rule(x, y, n, xcycle, xtarg, ytarg, ntarg)
References trapezoidal_cyclic.
Referenced by spectral_wave_bc_module::set_stationary_spectrum.
subroutine interp::interp_in_cyclic_function(x, y, n, xcycle, xp, np, yp)
Referenced by spectral_wave_bc_module::interpolate_spectrum, trapezoidal_cyclic.