wave_functions_module
subroutine wave_functions_module::slope2d(h, nx, ny, dsu, dnv, dhdx, dhdy, wete)
Referenced by wave_directions_module::wave_directions, wave_instationary_module::wave_instationary, wave_stationary_module::wave_stationary.
subroutine wave_functions_module::advecxho(ee, cgx, xadvec, nx, ny, ntheta, dnu, dsu, dsdnzi, scheme, wete)
References paramsconst::scheme_upwind_1, paramsconst::scheme_upwind_2, xmpi_module::xmpi_isbot, xmpi_module::xmpi_istop.
Referenced by wave_directions_module::wave_directions, wave_instationary_module::wave_instationary, wave_stationary_module::wave_stationary.
subroutine wave_functions_module::advecthetaho(ee, ctheta, thetaadvec, nx, ny, ntheta, dtheta, scheme, wete)
References paramsconst::scheme_upwind_1, paramsconst::scheme_upwind_2.
Referenced by wave_directions_module::wave_directions, wave_instationary_module::wave_instationary, wave_stationary_module::wave_stationary.
subroutine wave_functions_module::advecyho(ee, cgy, yadvec, nx, ny, ntheta, dsv, dnv, dsdnzi, scheme, wete)
References paramsconst::scheme_upwind_1, paramsconst::scheme_upwind_2.
Referenced by wave_directions_module::wave_directions, wave_instationary_module::wave_instationary, wave_stationary_module::wave_stationary.
subroutine wave_functions_module::advecwx(arrin2d, xwadvec, kmx, nx, ny, dsu, wete)
Referenced by wave_instationary_module::wave_instationary.
subroutine wave_functions_module::advecwy(arrin2d, ywadvec, kmy, nx, ny, dnv, wete)
Referenced by wave_instationary_module::wave_instationary.
subroutine wave_functions_module::advecqx(c, arrin2d, xwadvec, nx, ny, dsu, wete)
Referenced by wave_instationary_module::wave_instationary.
subroutine wave_functions_module::advecqy(c, arrin2d, ywadvec, nx, ny, dnv, wete)
Referenced by wave_instationary_module::wave_instationary.
subroutine wave_functions_module::dispersion(par, s)
References iteratedispersion.
Referenced by nonh_module::nonh_init_wcoef, boundaryconditions::wave_bc, initialize_module::wave_init, wave_instationary_module::wave_instationary, wave_stationary_module::wave_stationary.
elemental real*8 function wave_functions_module::iteratedispersion(L0, Lestimate, px, h)
Referenced by dispersion, spectral_wave_bc_module::generate_wavetrain_components, wave_boundary_update_module::generate_wavetrain_components, boundaryconditions::wave_bc.
subroutine wave_functions_module::breakerdelay(par, s)
References xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop.
Referenced by wave_instationary_module::wave_instationary, wave_stationary_module::wave_stationary.