spaceparams
subroutine spaceparams::indextos(s, index, t)
References xmpi_module::halt_program.
Referenced by ncoutput_module::fortoutput_init, means_module::makeaverage, means_module::makecrossvector, means_module::means_init, ncoutput_module::ncoutput, setvar, space_alloc_arrays_dummies.
subroutine spaceparams::index_allocate(s, par, index, choice)
Referenced by means_module::means_init, space_alloc_arrays_dummies.
logical function spaceparams::index_allocated(s, index)
subroutine spaceparams::space_alloc_scalars(s)
Referenced by demo, libxbeach_module::init, space_alloc_arrays_dummies.
subroutine spaceparams::space_alloc_arrays(s, par)
Referenced by space_alloc_arrays_dummies.
subroutine spaceparams::space_alloc_arrays_dummies(s, par)
References mnemmodule::chartoindex, logging_module::get_logfileid, xmpi_module::halt_program, index_allocate, indextos, mnemmodule::printvar, space_alloc_arrays, space_alloc_scalars, xmpi_module::xcompute, xmpi_module::xmaster, xmpi_module::xmpi_rank, xmpi_module::xmpi_size, xmpi_module::xomaster.
Referenced by libxbeach_module::init.
subroutine spaceparams::gridprops(s)
Referenced by initialize_module::grid_bathy.
subroutine spaceparams::ranges_init(s)
References xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop.
Referenced by libxbeach_module::init.