spectral_wave_bc_module
integer, dimension(:), allocatable spectral_wave_bc_module::n_index_loc
Referenced by generate_wave_train_properties_per_offshore_point, initialize_module::spectral_wave_init.
integer spectral_wave_bc_module::nspectra
Referenced by generate_combined_spectrum, generate_wave_train_properties_per_offshore_point, generate_wave_train_variance, set_reuseall, spectral_wave_bc, initialize_module::spectral_wave_init.
type(filenames), dimension(:), allocatable, public spectral_wave_bc_module::bcfiles
Referenced by set_reuseall, spectral_wave_bc, initialize_module::spectral_wave_init.
logical, public spectral_wave_bc_module::reuseall
Referenced by set_bcfilenames, set_reuseall, spectral_wave_bc, initialize_module::spectral_wave_init.
integer, save spectral_wave_bc_module::bccount
Referenced by generate_admin_files, set_bcfilenames, spectral_wave_bc, initialize_module::spectral_wave_init.
integer, save spectral_wave_bc_module::fidelist
Referenced by generate_admin_files.
integer, save spectral_wave_bc_module::fidqlist
Referenced by generate_admin_files.
integer, save spectral_wave_bc_module::fidnhlist
Referenced by generate_admin_files.
integer, save spectral_wave_bc_module::fideslist
Referenced by generate_admin_files.
real*8 spectral_wave_bc_module::spectrumendtime
Referenced by spectral_wave_bc, initialize_module::spectral_wave_init.
real*8, dimension(:,:), allocatable spectral_wave_bc_module::lastwaveelevation
Referenced by generate_ebcf, initialize_module::spectral_wave_init.
integer spectral_wave_bc_module::ind_end_taper
Referenced by generate_ebcf, generate_wave_time_axis.
integer, parameter, private spectral_wave_bc_module::nfint
Referenced by generate_combined_spectrum, generate_wave_train_variance, interpolate_spectrum.
integer, parameter, private spectral_wave_bc_module::naint
Referenced by generate_combined_spectrum, generate_wavetrain_components, interpolate_spectrum, read_jonswap_file.
integer, parameter, private spectral_wave_bc_module::kmin
Referenced by generate_wavetrain_components.
real*8, parameter, private spectral_wave_bc_module::wdmax
Referenced by generate_wavetrain_components.
real*8, parameter, private spectral_wave_bc_module::par_pi
subroutine spectral_wave_bc_module::spectral_wave_bc(s, par, curline)
References bccount, bcfiles, calculate_average_water_depth, filefunctions::create_new_fid, distribute_wave_train_directions, generate_admin_files, generate_combined_spectrum, generate_ebcf, generate_nhtimeseries_file, generate_qbcf, generate_swts, generate_wave_time_axis, generate_wave_train_fourier, generate_wave_train_properties_per_offshore_point, generate_wave_train_variance, generate_wavetrain_components, interpolate_spectrum, nspectra, read_spectrum_input, reuseall, set_bcfilenames, set_reuseall, set_stationary_spectrum, spectrumendtime, xmpi_module::xmaster.
Referenced by boundaryconditions::wave_bc.
subroutine spectral_wave_bc_module::read_spectrum_input(par, wp, fn, specin)
References filefunctions::create_new_fid, paramsconst::instat_jons, paramsconst::instat_jons_table, paramsconst::instat_swan, paramsconst::instat_vardens, read_jonswap_file, read_swan_file, read_vardens_file, logging_module::report_file_read_error.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::read_jonswap_file(par, wp, readfile, listline, specin)
References filefunctions::create_new_fid, paramsconst::instat_jons_table, readkey_module::issetparameter, jonswapgk, naint, readkey_module::readkey, readkey_module::readkey_dbl, readkey_module::readkey_dblvec, readkey_module::readkey_int, logging_module::report_file_read_error.
Referenced by read_spectrum_input.
subroutine spectral_wave_bc_module::jonswapgk(x, gam, y)
Referenced by read_jonswap_file.
subroutine spectral_wave_bc_module::read_swan_file(par, readfile, specin)
References filefunctions::create_new_fid, math_tools::flipa, math_tools::flipv, xmpi_module::halt_program, logging_module::report_file_read_error.
Referenced by read_spectrum_input.
subroutine spectral_wave_bc_module::read_vardens_file(par, readfile, specin)
References filefunctions::create_new_fid, math_tools::flipa, math_tools::flipv, xmpi_module::halt_program, logging_module::report_file_read_error.
Referenced by read_spectrum_input.
subroutine spectral_wave_bc_module::interpolate_spectrum(specin, specinterp, par, fmax)
References interp::interp_in_cyclic_function, interp::linear_interp, naint, nfint, tpdcalc.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::set_reuseall
References bcfiles, nspectra, reuseall.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::set_bcfilenames(wp)
References bccount, reuseall.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::generate_combined_spectrum(specinterp, combspec, px)
References naint, nfint, nspectra.
Referenced by spectral_wave_bc.
pure real*8 function spectral_wave_bc_module::calculate_average_water_depth(s)
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::generate_wavetrain_components(combspec, wp, par)
References frange, init_seed, wave_functions_module::iteratedispersion, kmin, interp::linear_interp, naint, math_tools::random, wdmax.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::tpdcalc(Sf, f, Trep, trepfac, switch)
Referenced by interpolate_spectrum.
subroutine spectral_wave_bc_module::frange(par, f, Sf, fmax, firstp, lastp, findlineout)
Referenced by generate_wavetrain_components.
subroutine spectral_wave_bc_module::init_seed(outseed)
Referenced by generate_wavetrain_components.
subroutine spectral_wave_bc_module::generate_wave_time_axis(par, wp)
References ind_end_taper.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::generate_wave_train_variance(wp, specinterp)
References interp::linear_interp, nfint, nspectra.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::generate_wave_train_properties_per_offshore_point(wp, s)
References interp::linear_interp, n_index_loc, nspectra.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::generate_wave_train_fourier(wp, s, par)
References math_tools::flipiv, logging_module::progress_indicator.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::distribute_wave_train_directions(wp, s, px, nspr, nonhspec)
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::generate_ebcf(wp, s, par)
References filefunctions::create_new_fid, math_tools::flipiv, math_tools::hilbert, ind_end_taper, lastwaveelevation, interp::linear_interp.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::generate_swts(wp, s)
References logging_module::progress_indicator.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::generate_qbcf(wp, s, par)
References filefunctions::create_new_fid, math_tools::flipiv, interp::linear_interp, logging_module::progress_indicator.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::generate_nhtimeseries_file(wp, par)
References filefunctions::create_new_fid.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::set_stationary_spectrum(s, par, wp, combspec)
References filefunctions::create_new_fid, interp::interp_using_trapez_rule.
Referenced by spectral_wave_bc.
subroutine spectral_wave_bc_module::generate_admin_files(par, wp, rtbc_local, dtbc_local, maindir_local, spectrumendtimeold, spectrumendtime)
References bccount, filefunctions::create_new_fid, fidelist, fideslist, fidnhlist, fidqlist.
Referenced by spectral_wave_bc.