getkey_module
subroutine getkey_module::getkey_indextype(par, key, index, type)
Referenced by getkey.
integer function getkey_module::getkey(par, key, value)
References getkey_indextype.
Referenced by introspection_module::getcharparameter_c, introspection_module::getdoubleparameter_c, introspection_module::getintparameter_c.
subroutine getkey_module::getnkeys(par, n)
subroutine getkey_module::getkeys(par, keys)