readkey_module
logical readkey_module::readkey_inio
Referenced by params::all_input, count_lines, issetparameter, parmapply, read_v_9, read_v_array, readkey_dbl, readkey_dblvec, readkey_int, readkey_name, readkey_str.
integer, parameter, private readkey_module::maxnames
character(slen), dimension(maxnames), private readkey_module::allowednames
Referenced by parmapply, setallowednames.
character(slen), dimension(maxnames), private readkey_module::oldnames
Referenced by parmapply, setoldnames.
character(slen), private readkey_module::varname
integer, dimension(maxnames), private readkey_module::intvalues
Referenced by parmapply, setallowednames.
integer, private readkey_module::numallowednames
Referenced by parmapply, setallowednames.
integer, private readkey_module::numoldnames
Referenced by parmapply, setallowednames, setoldnames.
real*8 function readkey_module::readkey_dbl(fname, key, defval, mnval, mxval, bcast, required, silent, strict)
References xmpi_module::halt_program, readkey, readkey_inio, logging_module::report_file_read_error, xmpi_module::xmaster.
Referenced by params::all_input, waveparams::build_jonswap, waveparams::makebcf, wave_boundary_update_module::read_jonswap_file, spectral_wave_bc_module::read_jonswap_file, ship_module::ship_init, waveparams::swanreader.
integer*4 function readkey_module::readkey_int(fname, key, defval, mnval, mxval, bcast, required, silent, strict)
References xmpi_module::halt_program, readkey, readkey_inio, logging_module::report_file_read_error, xmpi_module::xmaster.
Referenced by params::all_input, wave_boundary_update_module::read_jonswap_file, spectral_wave_bc_module::read_jonswap_file, ship_module::ship_init, vegetation_module::veggie_init.
character(slen) function readkey_module::readkey_str(fname, key, defval, nv, nov, allowed, old, bcast, required, silent)
References xmpi_module::halt_program, lowercase, readkey, readkey_inio, typesandkinds::slen, xmpi_module::xmaster.
Referenced by parmapply.
character(slen) function readkey_module::readkey_name(fname, key, bcast, required, silent)
References xmpi_module::halt_program, readkey, readkey_inio, typesandkinds::slen, xmpi_module::xmaster.
Referenced by params::all_input, ship_module::ship_init.
real*8 function, dimension(tlength) readkey_module::readkey_dblvec(fname, key, vlength, tlength, defval, mnval, mxval, bcast, required, silent)
References xmpi_module::halt_program, readkey, readkey_inio, typesandkinds::slen, xmpi_module::xmaster.
Referenced by params::all_input, wave_boundary_update_module::read_jonswap_file, spectral_wave_bc_module::read_jonswap_file, vegetation_module::veggie_init.
logical function readkey_module::issetparameter(fname, key, bcast)
References readkey, readkey_inio, xmpi_module::xmaster.
Referenced by params::all_input, wave_boundary_update_module::read_jonswap_file, spectral_wave_bc_module::read_jonswap_file, params::readpointvars.
subroutine readkey_module::readkey(fname, key, value)
References typesandkinds::slen, strippedline, uppercase.
Referenced by params::all_input, waveparams::build_jonswap, issetparameter, wave_boundary_update_module::read_jonswap_file, spectral_wave_bc_module::read_jonswap_file, readkey_dbl, readkey_dblvec, readkey_int, readkey_name, readkey_str.
pure character(slen) function readkey_module::uppercase(STR)
Referenced by readkey.
subroutine readkey_module::lowercase(STR)
Referenced by readkey_str, boundaryconditions::velocity_boundary.
subroutine readkey_module::parmapply(vname, idefname, parm, parm_str, bcast, required)
References allowednames, intvalues, numallowednames, numoldnames, oldnames, readkey_inio, readkey_str, xmpi_module::xmaster.
Referenced by params::all_input.
subroutine readkey_module::setallowednames(a1, v1, a2, v2, a3, v3, a4, v4, a5, v5, a6, v6, a7, v7, a8, v8, a9, v9, a10, v10, a11, v11, a12, v12, a13, v13, a14, v14, a15, v15, a16, v16, a17, v17, a18, v18, a19, v19, a20, v20)
References allowednames, intvalues, numallowednames, numoldnames.
Referenced by params::all_input.
subroutine readkey_module::setoldnames(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20)
References numoldnames, oldnames.
Referenced by params::all_input.
subroutine readkey_module::read_v_array(fid, a)
References readkey_inio, xmpi_module::xmaster.
subroutine readkey_module::read_v_9(fid, a, a1, a2, a3, a4, a5, a6, a7, a8)
References readkey_inio, xmpi_module::xmaster.
integer function readkey_module::count_lines(f)
References filefunctions::create_new_fid, readkey_inio, xmpi_module::xmaster.
Referenced by ship_module::ship_init.
character(slen) function readkey_module::strippedline(line)
References typesandkinds::slen.
Referenced by readkey, params::readpointposition.