math_tools
integer, parameter, public math_tools::fftkind
Referenced by transform.
integer, parameter, public math_tools::realkind
real(fftkind), parameter math_tools::sin60
Referenced by fftradix.
real(fftkind), parameter math_tools::cos72
Referenced by fftradix.
real(fftkind), parameter math_tools::sin72
Referenced by fftradix.
real(fftkind), parameter math_tools::pi
Referenced by fftradix.
complex(fftkind) function, dimension(size(array, 1)) math_tools::fft1d(array, dim, inv, stat)
References fftn.
complex(fftkind) function, dimension(size(array, 1), size(array, 2)) math_tools::fft2d(array, dim, inv, stat)
References fftn.
complex(fftkind) function, dimension(size(array, 1), size(array, 2), size(array, 3)) math_tools::fft3d(array, dim, inv, stat)
References fftn.
complex(fftkind) function, dimension( size(array, 1), size(array, 2), size(array, 3), size(array, 4)) math_tools::fft4d(array, dim, inv, stat)
References fftn.
complex(fftkind) function, dimension( size(array, 1), size(array, 2), size(array, 3), size(array, 4), size(array, 5)) math_tools::fft5d(array, dim, inv, stat)
References fftn.
complex(fftkind) function, dimension( size(array, 1), size(array, 2), size(array, 3), size(array, 4), size(array, 5), size(array, 6)) math_tools::fft6d(array, dim, inv, stat)
References fftn.
complex(fftkind) function, dimension( size(array, 1), size(array, 2), size(array, 3), size(array, 4), size(array, 5), size(array, 6), size(array, 7)) math_tools::fft7d(array, dim, inv, stat)
References fftn.
subroutine, public math_tools::fftn(array, shape, dim, inv, stat)
References fftradix.
Referenced by fft1d, fft2d, fft3d, fft4d, fft5d, fft6d, fft7d.
subroutine math_tools::fftradix(array, ntotal, npass, nspan, inv, stat)
References cos72, factorize, permute, pi, sin60, sin72, transform.
Referenced by fftn.
subroutine, public math_tools::hilbert(xi, m)
Referenced by waveparams::build_etdir, wave_boundary_update_module::generate_ebcf, spectral_wave_bc_module::generate_ebcf.
subroutine, public math_tools::flipv(x, M)
Referenced by wave_boundary_update_module::read_swan_file, spectral_wave_bc_module::read_swan_file, spectral_wave_bc_module::read_vardens_file, wave_boundary_update_module::read_vardens_file, waveparams::swanreader.
subroutine, public math_tools::flipiv(x, M)
Referenced by waveparams::build_boundw, waveparams::build_etdir, wave_boundary_update_module::generate_ebcf, spectral_wave_bc_module::generate_ebcf, wave_boundary_update_module::generate_qbcf, spectral_wave_bc_module::generate_qbcf, spectral_wave_bc_module::generate_wave_train_fourier, wave_boundary_update_module::generate_wave_train_fourier.
subroutine, public math_tools::flipa(x, M1, M2, flip)
References xmpi_module::halt_program.
Referenced by wave_boundary_update_module::read_swan_file, spectral_wave_bc_module::read_swan_file, spectral_wave_bc_module::read_vardens_file, wave_boundary_update_module::read_vardens_file, waveparams::swanreader.
real*8 function, dimension(size(x)), public math_tools::xerf(x)
Referenced by roelvink_module::janssen_battjes_1d.
real*8 function, public math_tools::random(j)
Referenced by waveparams::build_etdir, spectral_wave_bc_module::generate_wavetrain_components, wave_boundary_update_module::generate_wavetrain_components, waveparams::init_seed.