groundwaterflow
subroutine, public groundwaterflow::gw_init(s, par)
References xmpi_module::xmaster, xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop.
Referenced by libxbeach_module::init.
subroutine, public groundwaterflow::gw_bc(s, par)
References xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop.
Referenced by libxbeach_module::executestep.
subroutine, public groundwaterflow::gwflow(s, par)
References gw_calculate_hydrostatic_w, gw_calculate_interfaceheight, gw_calculate_smoothwetlayer, gw_calculate_velocities, gw_horizontal_infil_exfil, gw_solver, gw_unconnected_infil, gwcalculateheadbottom, gwcalculateheadtop, xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop.
Referenced by libxbeach_module::executestep.
subroutine groundwaterflow::gw_unconnected_infil(s, par, Kzinf, connected, fracdt, infil)
References gw_calc_local_infil.
Referenced by gwflow.
subroutine groundwaterflow::gw_calculate_interfaceheight(s, gwhu, gwhv, initial)
References xmpi_module::xmpi_isbot, xmpi_module::xmpi_isright.
Referenced by gwflow.
pure real*8 function, dimension(s%nx+1,s%ny+1) groundwaterflow::gw_calculate_smoothwetlayer(s, dwetlayer, px)
Referenced by gwflow.
pure real*8 function, dimension(nx+1,ny+1) groundwaterflow::gwcalculateheadtop(nx, ny, zs, gwlevel, wetz, r, nonh, g, pres)
Referenced by gwflow.
pure subroutine groundwaterflow::gwcalculateheadgradient(nx, ny, gwhead, dsu, dnv, dheaddx, dheaddy)
Referenced by gw_calculate_velocities.
subroutine groundwaterflow::gw_solver(par, s, hbc, Kx, Ky, Kz, hu, hv, fracdt)
References solver_module::solver_sip, solver_module::solver_tridiag.
Referenced by gwflow.
subroutine groundwaterflow::gw_horizontal_infil_exfil(s, par, infilhorgw, infilhorsw, Kx, dynpres)
References gw_calculate_velocities_local.
Referenced by gwflow.
subroutine groundwaterflow::gw_calculate_velocities(s, par, fracdt, gwu, gwv, gww, Kx, Ky, Kz, Kxupd, Kyupd, Kzupd)
References gw_calculate_velocities_local, gwcalculateheadgradient, xmpi_module::xmpi_isleft, xmpi_module::xmpi_istop.
Referenced by gwflow.
pure subroutine groundwaterflow::gw_calculate_velocities_local(vel, Kupd, headgrad, Kin, fracdt, gwscheme, isvert, isnonh, headmodel, gwc, gwh, vcr)
References paramsconst::gwheadmodel_exponential, paramsconst::gwheadmodel_parabolic, paramsconst::gwscheme_laminar, paramsconst::gwscheme_turbulent.
Referenced by gw_calculate_velocities, gw_horizontal_infil_exfil.
real*8 function, dimension(:,:), pointer groundwaterflow::gw_calculate_hydrostatic_w(s, par, ratio)
References gw_calc_local_infil, xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop.
Referenced by gwflow.
pure subroutine groundwaterflow::gw_calc_local_infil(par, zb, hh, gwlevel, kzlocal, dinfil, D50top, turb, fracdt, infil, kzupd)
Referenced by gw_calculate_hydrostatic_w, gw_unconnected_infil.
pure real*8 function, dimension(nx+1,ny+1) groundwaterflow::gwcalculateheadbottom(gwcurv, gwheadtop, gwheight, nx, ny, model)
References paramsconst::gwheadmodel_exponential, paramsconst::gwheadmodel_parabolic.
Referenced by gwflow.