iso_c_utils
integer(c_int), parameter iso_c_utils::maxstringlen
integer(c_int) pure function iso_c_utils::strlen(char_array)
Referenced by char_array_to_string, strcpy.
integer(c_int) pure function iso_c_utils::strcmp(char_array1, char_array2)
References char_array_to_string.
subroutine iso_c_utils::strcpy(str1, str2)
References strlen.
pure character(len=strlen(char_array)) function iso_c_utils::char_array_to_string(char_array)
References strlen.
Referenced by xbeach_bmi::get_var_rank, xbeach_bmi::get_var_type, xbeach_bmi::initialize, strcmp.
pure character(kind=c_char,len=1) function, dimension(maxstringlen) iso_c_utils::string_to_char_array(string)
Referenced by xbeach_bmi::get_var_type, logging_module::logmsg.