params
logical params::params_inio
Referenced by libxbeach_module::init.
subroutine params::all_input(par)
References paramsconst::back_abs_1d, paramsconst::back_abs_2d, paramsconst::back_wall, paramsconst::back_wlevel, paramsconst::bdslpeffdir_none, paramsconst::bdslpeffdir_talmon, paramsconst::bdslpeffini_bed, paramsconst::bdslpeffini_none, paramsconst::bdslpeffini_total, paramsconst::bdslpeffmag_none, paramsconst::bdslpeffmag_roelv_bed, paramsconst::bdslpeffmag_roelv_total, paramsconst::bdslpeffmag_souls_bed, paramsconst::bdslpeffmag_souls_total, paramsconst::bedfriction_cf, paramsconst::bedfriction_chezy, paramsconst::bedfriction_manning, paramsconst::bedfriction_white_colebrook, paramsconst::bedfriction_white_colebrook_grainsize, paramsconst::break_baldock, paramsconst::break_janssen, paramsconst::break_roelvink1, paramsconst::break_roelvink2, paramsconst::break_roelvink_daly, filefunctions::check_file_exist, filefunctions::checkbcfilelength, paramsconst::form_soulsby_vanrijn, paramsconst::form_vanthiel_vanrijn, paramsconst::front_abs_1d, paramsconst::front_abs_2d, paramsconst::front_nonh_1d, paramsconst::front_wall, paramsconst::front_waveflume, paramsconst::front_wlevel, filefunctions::get_file_length, paramsconst::gridform_delft3d, paramsconst::gridform_xbeach, paramsconst::gwheadmodel_exponential, paramsconst::gwheadmodel_parabolic, paramsconst::gwscheme_laminar, paramsconst::gwscheme_turbulent, xmpi_module::halt_program, paramsconst::instat_bichrom, paramsconst::instat_jons, paramsconst::instat_jons_table, paramsconst::instat_off, paramsconst::instat_reuse, paramsconst::instat_stat, paramsconst::instat_stat_table, paramsconst::instat_swan, paramsconst::instat_ts_1, paramsconst::instat_ts_2, paramsconst::instat_ts_nonh, paramsconst::instat_vardens, readkey_module::issetparameter, paramsconst::lateralwave_cyclic, paramsconst::lateralwave_neumann, paramsconst::lateralwave_wavecrest, paramsconst::lr_neumann, paramsconst::lr_neumann_v, paramsconst::lr_no_advec, paramsconst::lr_wall, paramsconst::outputformat_debug, paramsconst::outputformat_fortran, paramsconst::outputformat_netcdf, paramsconst::outputprecision_double, paramsconst::outputprecision_single, readkey_module::parmapply, paramsconst::paulrevere_land, paramsconst::paulrevere_sea, readglobalvars, readkey_module::readkey, readkey_module::readkey_dbl, readkey_module::readkey_dblvec, readkey_module::readkey_inio, readkey_module::readkey_int, readkey_module::readkey_name, readmeans, readpointvars, logging_module::report_file_read_error, paramsconst::scheme_lax_wendroff, paramsconst::scheme_upwind_1, paramsconst::scheme_upwind_2, readkey_module::setallowednames, readkey_module::setoldnames, paramsconst::solver_sipp, paramsconst::solver_tridiagg, paramsconst::tidetype_instant, paramsconst::tidetype_velocity, paramsconst::turb_bore_averaged, paramsconst::turb_none, paramsconst::turb_wave_averaged, paramsconst::turbadv_eulerian, paramsconst::turbadv_lagrangian, paramsconst::turbadv_none, paramsconst::waveform_ruessink_vanrijn, paramsconst::waveform_vanthiel, xmpi_module::xmaster, xmpi_module::xmpi_size.
Referenced by libxbeach_module::init.
subroutine params::readglobalvars(par)
References readoutputstrings, xmpi_module::xmaster.
Referenced by all_input.
subroutine params::readpointvars(par)
References xmpi_module::halt_program, readkey_module::issetparameter, readoutputstrings, readpointposition, xmpi_module::xmaster.
Referenced by all_input.
subroutine params::readmeans(par)
References readoutputstrings.
Referenced by all_input.
subroutine params::readoutputstrings(par, readtype)
References mnemmodule::chartoindex, xmpi_module::halt_program, logging_module::report_file_read_error, xmpi_module::xmaster.
Referenced by readglobalvars, readmeans, readpointvars.
subroutine params::readpointposition(par, readtype, xpoints, ypoints)
References xmpi_module::halt_program, readkey_module::strippedline, xmpi_module::xmaster.
Referenced by readpointvars.