boundaryconditions
subroutine boundaryconditions::wave_bc(sg, sl, par)
References wave_functions_module::dispersion, paramsconst::instat_bichrom, paramsconst::instat_jons, paramsconst::instat_jons_table, paramsconst::instat_reuse, paramsconst::instat_stat, paramsconst::instat_stat_table, paramsconst::instat_swan, paramsconst::instat_ts_1, paramsconst::instat_ts_2, paramsconst::instat_ts_nonh, paramsconst::instat_vardens, wave_functions_module::iteratedispersion, interp::linear_interp, nonh_module::nonh_init_wcoef, logging_module::report_file_read_error, spectral_wave_bc_module::spectral_wave_bc, velocity_boundary, xmpi_module::xmaster, xmpi_module::xmpi_istop.
Referenced by libxbeach_module::executestep.
subroutine boundaryconditions::flow_bc(s, par)
References paramsconst::back_abs_1d, paramsconst::back_abs_2d, paramsconst::back_wall, paramsconst::back_wlevel, paramsconst::front_abs_1d, paramsconst::front_abs_2d, paramsconst::front_nonh_1d, paramsconst::front_wall, paramsconst::front_waveflume, paramsconst::front_wlevel, paramsconst::instat_off, interp::linear_interp, paramsconst::paulrevere_land, paramsconst::paulrevere_sea, paramsconst::tidetype_instant, paramsconst::tidetype_velocity, xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop.
Referenced by libxbeach_module::executestep.
real*8 function, dimension(s%nx+1) boundaryconditions::flow_lat_bc(s, par, bctype, jbc, jn, udvdxb, vdvdyb, viscvb)
References paramsconst::lr_neumann, paramsconst::lr_neumann_v, paramsconst::lr_no_advec, paramsconst::lr_wall.
Referenced by flow_timestep_module::flow.
subroutine boundaryconditions::discharge_boundary_h(s, par)
References interp::linear_interp, xmpi_module::xmpi_isbot, xmpi_module::xmpi_isleft, xmpi_module::xmpi_isright, xmpi_module::xmpi_istop, xmpi_module::xmpi_rank.
Referenced by flow_timestep_module::flow.
subroutine boundaryconditions::discharge_boundary_v(s, par)
References interp::linear_interp, xmpi_module::xmpi_rank.
Referenced by flow_timestep_module::flow.
subroutine boundaryconditions::velocity_boundary(bcfile, ug, zg, wg, dug, nyg, t, isSet_U, isSet_Z, isSet_W, isSet_dU, isSet_Q, force_init, bcst)
References xmpi_module::halt_program, readkey_module::lowercase, logging_module::report_file_read_error, velocity_boundary_read.
Referenced by wave_bc.
subroutine boundaryconditions::velocity_boundary_read(t, vector, iUnit, isvec, iseof, nvar)
References xmpi_module::halt_program, logging_module::report_file_read_error.
Referenced by velocity_boundary.