ncoutput_module
integer ncoutput_module::ncid
Referenced by ncoutput.
integer ncoutput_module::parvarid
integer ncoutput_module::xdimid
Referenced by ncoutput.
integer ncoutput_module::ydimid
Referenced by ncoutput.
integer ncoutput_module::xvarid
integer ncoutput_module::yvarid
integer ncoutput_module::thetadimid
Referenced by ncoutput.
integer ncoutput_module::sedimentclassesdimid
Referenced by ncoutput.
integer ncoutput_module::bedlayersdimid
Referenced by ncoutput.
integer ncoutput_module::driftersdimid
Referenced by ncoutput.
integer ncoutput_module::driftersdimid2
integer ncoutput_module::drifterstimedimid
integer ncoutput_module::drifterstimevarid
Referenced by ncoutput.
integer, dimension(:), allocatable ncoutput_module::driftersvarids
Referenced by ncoutput.
real*8, dimension(3) ncoutput_module::drift
Referenced by ncoutput.
integer ncoutput_module::shipdimid
Referenced by ncoutput.
integer, dimension(:), allocatable ncoutput_module::globalvarids
Referenced by ncoutput.
integer ncoutput_module::pointsdimid
integer ncoutput_module::pointnamelengthdimid
integer ncoutput_module::xpointsvarid
integer ncoutput_module::ypointsvarid
integer ncoutput_module::pointtypesvarid
integer ncoutput_module::xpointindexvarid
integer ncoutput_module::ypointindexvarid
integer ncoutput_module::stationidvarid
integer, dimension(:), allocatable ncoutput_module::pointsvarids
Referenced by ncoutput.
integer, dimension(:), allocatable ncoutput_module::xpoints
Referenced by ncoutput, points_output_init.
integer, dimension(:), allocatable ncoutput_module::ypoints
Referenced by ncoutput, points_output_init.
integer, dimension(:,:), allocatable ncoutput_module::meanvarids
Referenced by ncoutput.
character(slen), dimension(:), allocatable ncoutput_module::meanvartypes
Referenced by ncoutput.
integer*4 ncoutput_module::nmeanvartypes
Referenced by ncoutput.
integer*4, dimension(:), allocatable ncoutput_module::rugrowindex
Referenced by ncoutput, points_output_init.
integer ncoutput_module::globaltimedimid
integer ncoutput_module::pointtimedimid
integer ncoutput_module::meantimedimid
integer ncoutput_module::globaltimevarid
Referenced by ncoutput.
integer ncoutput_module::pointtimevarid
Referenced by ncoutput.
integer ncoutput_module::meantimevarid
Referenced by ncoutput.
integer ncoutput_module::tidetimedimid
Referenced by ncoutput.
integer ncoutput_module::windtimedimid
Referenced by ncoutput.
integer ncoutput_module::inoutdimid
Referenced by ncoutput.
integer ncoutput_module::tidecornersdimid
Referenced by ncoutput.
integer ncoutput_module::npointstotal
integer ncoutput_module::itg
Referenced by fortoutput_init, ncoutput.
integer ncoutput_module::itp
Referenced by fortoutput_init, ncoutput.
integer ncoutput_module::itc
Referenced by fortoutput_init, ncoutput.
integer ncoutput_module::itm
Referenced by fortoutput_init, ncoutput.
integer ncoutput_module::itd
Referenced by fortoutput_init, ncoutput.
integer ncoutput_module::stpm
Referenced by fortoutput_init, ncoutput.
integer ncoutput_module::wordsize
Referenced by fortoutput_init, ncoutput.
integer ncoutput_module::noutnumbers
Referenced by fortoutput_init.
integer, dimension(numvars) ncoutput_module::outnumbers
Referenced by checkfile, fortoutput_init.
integer ncoutput_module::ncreal
subroutine, public ncoutput_module::ncoutput(s, sl, par, tpar)
References bedlayersdimid, mnemmodule::chartoindex, checkfile, drift, driftersdimid, drifterstimevarid, driftersvarids, postprocessmod::get_sister_mnem, globaltimevarid, globalvarids, indextodrifterunit, indextomaxunit, indextomeanunit, indextominunit, indextopointsunit, spaceparams::indextos, indextovarunit, inoutdimid, itc, itd, itg, itm, itp, means_module::meansparsglobal, means_module::meansparslocal, meantimevarid, meanvarids, meanvartypes, ncid, nmeanvartypes, pointsvarids, pointtimevarid, rugrowindex, sedimentclassesdimid, shipdimid, stpm, thetadimid, tidecornersdimid, tidetimedimid, windtimedimid, wordsize, xmpi_module::xcompute, xdimid, xmpi_module::xmaster, xmpi_module::xmpi_orank, xmpi_module::xmpi_rank, xmpi_module::xomaster, xpoints, ydimid, ypoints.
Referenced by output_module::output.
subroutine, public ncoutput_module::points_output_init(s, par)
References rugrowindex, postprocessmod::snappointstogrid, xmpi_module::xomaster, xpoints, ypoints.
Referenced by output_module::output_init.
subroutine, public ncoutput_module::fortoutput_init(s, par, tpar)
References mnemmodule::chartoindex, filefunctions::create_new_fid, indextodrifterunit, indextomaxunit, indextomeanunit, indextominunit, indextopointsunit, spaceparams::indextos, indextovarunit, itc, itd, itg, itm, itp, makeaveragenames, noutnumbers, outnumbers, stpm, wordsize, xmpi_module::xomaster.
Referenced by output_module::output_init.
subroutine ncoutput_module::checkfile(index, unit, reclen, jtg)
References indextoglobalunit, outnumbers.
Referenced by ncoutput.
integer function ncoutput_module::outunit(ind, s)
References xmpi_module::halt_program.
Referenced by indextodrifterunit, indextoglobalunit, indextomaxunit, indextomeanunit, indextominunit, indextopointsunit, indextovarunit.
integer function ncoutput_module::indextopointsunit(index)
References outunit.
Referenced by fortoutput_init, ncoutput.
integer function ncoutput_module::indextoglobalunit(index)
References outunit.
Referenced by checkfile.
integer function ncoutput_module::indextomeanunit(index)
References outunit.
Referenced by fortoutput_init, ncoutput.
integer function ncoutput_module::indextominunit(index)
References outunit.
Referenced by fortoutput_init, ncoutput.
integer function ncoutput_module::indextomaxunit(index)
References outunit.
Referenced by fortoutput_init, ncoutput.
integer function ncoutput_module::indextovarunit(index)
References outunit.
Referenced by fortoutput_init, ncoutput.
integer function ncoutput_module::indextodrifterunit(index)
References outunit.
Referenced by fortoutput_init, ncoutput.
subroutine ncoutput_module::makeaveragenames(counter, fnamemean, fnamevar, fnamemin, fnamemax)
Referenced by fortoutput_init.