logging_module
integer, save logging_module::logfileid
Referenced by close_logfiles, get_logfileid, start_logfiles, writelog_distribute.
integer, save logging_module::errorfileid
Referenced by close_logfiles, get_logfileid, start_logfiles, writelog_distribute.
integer, save logging_module::warningfileid
Referenced by close_logfiles, get_logfileid, start_logfiles, writelog_distribute.
procedure(ilogger), pointer logging_module::logging_callback
Referenced by logmsg, set_logger, writelog_distribute, writelog_finalize.
integer, parameter, public logging_module::level_all
integer, parameter, public logging_module::level_debug
integer, parameter, public logging_module::level_info
integer, parameter, public logging_module::level_warn
integer, parameter, public logging_module::level_error
integer, parameter, public logging_module::level_fatal
integer, parameter, public logging_module::level_off
subroutine logging_module::set_logger(c_callback)
References logging_callback.
subroutine logging_module::logmsg(level, msg)
References logging_callback, iso_c_utils::string_to_char_array.
Referenced by writelog_distribute.
subroutine logging_module::start_logfiles(error)
References errorfileid, generate_logfileid, logfileid, warningfileid, xmpi_module::xmaster.
Referenced by libxbeach_module::init.
subroutine logging_module::close_logfiles
References errorfileid, logfileid, warningfileid, xmpi_module::xmaster.
Referenced by writelog_finalize.
subroutine logging_module::get_logfileid(lid, eid, wid)
References errorfileid, logfileid, warningfileid.
Referenced by spaceparams::space_alloc_arrays_dummies.
integer function logging_module::generate_logfileid()
Referenced by start_logfiles.
subroutine logging_module::progress_indicator(initialize, curper, dper, dt)
Referenced by wave_boundary_update_module::generate_qbcf, spectral_wave_bc_module::generate_qbcf, wave_boundary_update_module::generate_swts, spectral_wave_bc_module::generate_swts, spectral_wave_bc_module::generate_wave_train_fourier, wave_boundary_update_module::generate_wave_train_fourier.
subroutine logging_module::report_file_read_error(filename)
References xmpi_module::halt_program.
Referenced by params::all_input, filefunctions::checkbcfilelength, initialize_module::discharge_init, initialize_module::drifter_init, initialize_module::flow_init, initialize_module::grid_bathy, wave_boundary_update_module::read_jonswap_file, spectral_wave_bc_module::read_jonswap_file, wave_boundary_update_module::read_spectrum_input, spectral_wave_bc_module::read_spectrum_input, wave_boundary_update_module::read_swan_file, spectral_wave_bc_module::read_swan_file, spectral_wave_bc_module::read_vardens_file, wave_boundary_update_module::read_vardens_file, readkey_module::readkey_dbl, readkey_module::readkey_int, params::readoutputstrings, readtide_module::readtide, readwind_module::readwind, initialize_module::sed_init, initialize_module::setbathy_init, timestep_module::timestep_init, boundaryconditions::velocity_boundary, boundaryconditions::velocity_boundary_read, boundaryconditions::wave_bc.
subroutine logging_module::writelog_startup()
References xmpi_module::halt_program, xmpi_module::xmaster, xmpi_module::xmpi_size.
Referenced by libxbeach_module::init.
subroutine logging_module::writelog_finalize(tbegin, n, t, nx, ny, t0, t01)
References close_logfiles, logging_callback, xmpi_module::xmaster, xmpi_module::xmpi_size.
Referenced by libxbeach_module::final.
subroutine logging_module::writelog_distribute(destination, display)
References errorfileid, logfileid, logging_callback, logmsg, warningfileid, xmpi_module::xmaster.