wave_boundary_update_module
integer, parameter wave_boundary_update_module::nfint
Referenced by generate_combined_spectrum, generate_wave_train_variance, interpolate_spectrum.
integer, parameter wave_boundary_update_module::naint
Referenced by generate_combined_spectrum, generate_wavetrain_components, interpolate_spectrum, read_jonswap_file.
integer, parameter wave_boundary_update_module::kmin
Referenced by generate_wavetrain_components.
real*8, parameter wave_boundary_update_module::wdmax
Referenced by generate_wavetrain_components.
integer wave_boundary_update_module::nspectra
Referenced by generate_combined_spectrum, generate_wave_boundary_surfbeat, generate_wave_train_properties_per_offshore_point, generate_wave_train_variance, set_repeatwbc.
integer wave_boundary_update_module::bccount
Referenced by generate_ebcf, generate_wave_boundary_surfbeat, set_bcfilenames.
integer wave_boundary_update_module::npb
Referenced by generate_ebcf, generate_nhtimeseries_file, generate_qbcf, generate_swts, generate_wave_boundary_surfbeat, generate_wave_train_fourier.
real*8 wave_boundary_update_module::hb0
Referenced by generate_qbcf, generate_swts, generate_wave_boundary_surfbeat, generate_wavetrain_components.
real*8, parameter wave_boundary_update_module::par_pi
Referenced by distribute_wave_train_directions, generate_combined_spectrum, generate_qbcf, generate_wave_boundary_surfbeat, generate_wavetrain_components, interpolate_spectrum, read_jonswap_file, read_swan_file, read_vardens_file.
real*8, parameter wave_boundary_update_module::par_g
Referenced by generate_ebcf, generate_qbcf, generate_wavetrain_components, read_swan_file.
complex(kind(0.0d0)), parameter wave_boundary_update_module::par_compi
Referenced by generate_qbcf, generate_wave_train_fourier.
subroutine, public wave_boundary_update_module::generate_wave_boundary_surfbeat(durationlength)
References bccount, distribute_wave_train_directions, generate_combined_spectrum, generate_ebcf, generate_nhtimeseries_file, generate_qbcf, generate_swts, generate_wave_time_axis, generate_wave_train_fourier, generate_wave_train_properties_per_offshore_point, generate_wave_train_variance, generate_wavetrain_components, hb0, interpolate_spectrum, npb, nspectra, par_pi, read_spectrum_input, set_repeatwbc, wave_boundary_datastore::waveboundaryadministration, wave_boundary_datastore::waveboundaryparameters, wave_boundary_datastore::waveboundarytimeseries, wave_boundary_datastore::wavespectrumadministration.
Referenced by wave_boundary_main_module::create_incident_waves_surfbeat.
subroutine wave_boundary_update_module::read_spectrum_input(wp, fn, specin)
References filefunctions::create_new_fid, read_jonswap_file, read_swan_file, read_vardens_file, logging_module::report_file_read_error.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::read_jonswap_file(par, wp, readfile, listline, specin)
References filefunctions::create_new_fid, readkey_module::issetparameter, jonswapgk, naint, par_pi, readkey_module::readkey, readkey_module::readkey_dbl, readkey_module::readkey_dblvec, readkey_module::readkey_int, logging_module::report_file_read_error.
Referenced by read_spectrum_input.
subroutine wave_boundary_update_module::jonswapgk(x, gam, y)
Referenced by read_jonswap_file.
subroutine wave_boundary_update_module::read_swan_file(par, readfile, specin)
References filefunctions::create_new_fid, math_tools::flipa, math_tools::flipv, xmpi_module::halt_program, par_g, par_pi, logging_module::report_file_read_error, wave_boundary_datastore::waveboundaryparameters.
Referenced by read_spectrum_input.
subroutine wave_boundary_update_module::read_vardens_file(par, readfile, specin)
References filefunctions::create_new_fid, math_tools::flipa, math_tools::flipv, xmpi_module::halt_program, par_pi, logging_module::report_file_read_error.
Referenced by read_spectrum_input.
subroutine wave_boundary_update_module::interpolate_spectrum(specin, specinterp, par, fmax)
References interp::linear_interp, interp::linear_interp_2d, naint, nfint, par_pi, tpdcalc.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::set_repeatwbc
References nspectra, wave_boundary_datastore::wavespectrumadministration.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::set_bcfilenames(wp)
References bccount, wave_boundary_datastore::wavespectrumadministration.
subroutine wave_boundary_update_module::generate_combined_spectrum(specinterp, combspec)
References naint, nfint, nspectra, par_pi, tpdcalc.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::generate_wavetrain_components(combspec, wp)
References frange, hb0, wave_functions_module::iteratedispersion, kmin, interp::linear_interp, naint, par_g, par_pi, math_tools::random, wave_boundary_datastore::waveboundaryparameters, wdmax.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::tpdcalc(Sf, f, Trep, trepfac, switch)
Referenced by generate_combined_spectrum, interpolate_spectrum.
subroutine wave_boundary_update_module::frange(f, Sf, fmax, firstp, lastp, findlineout)
References wave_boundary_datastore::waveboundaryparameters.
Referenced by generate_wavetrain_components.
subroutine wave_boundary_update_module::generate_wave_time_axis(wp)
References wave_boundary_datastore::waveboundaryparameters, wave_boundary_datastore::wavespectrumadministration.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::generate_wave_train_variance(wp, specinterp)
References interp::linear_interp, nfint, nspectra.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::generate_wave_train_properties_per_offshore_point(wp, s)
References interp::linear_interp, nspectra.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::generate_wave_train_fourier(wp)
References math_tools::flipiv, npb, par_compi, logging_module::progress_indicator, wave_boundary_datastore::waveboundaryparameters.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::distribute_wave_train_directions(wp, nspr)
References par_pi, wave_boundary_datastore::waveboundaryparameters.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::generate_ebcf(wp)
References bccount, math_tools::flipiv, math_tools::hilbert, interp::linear_interp, npb, par_g, wave_boundary_datastore::waveboundaryadministration, wave_boundary_datastore::waveboundaryparameters, wave_boundary_datastore::waveboundarytimeseries.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::generate_swts(wp)
References hb0, npb, logging_module::progress_indicator, wave_boundary_datastore::waveboundaryparameters.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::generate_qbcf(wp)
References math_tools::flipiv, hb0, interp::linear_interp, npb, par_compi, par_g, par_pi, logging_module::progress_indicator, wave_boundary_datastore::waveboundaryparameters, wave_boundary_datastore::waveboundarytimeseries.
Referenced by generate_wave_boundary_surfbeat.
subroutine wave_boundary_update_module::generate_nhtimeseries_file(wp)
References npb, wave_boundary_datastore::waveboundarytimeseries.
Referenced by generate_wave_boundary_surfbeat.