vegetation_module
subroutine, public vegetation_module::veggie_init(s, par, veg)
References filefunctions::check_file_exist, filefunctions::create_new_fid, readkey_module::readkey_dblvec, readkey_module::readkey_int, xmpi_module::xmaster.
Referenced by libxbeach_module::init.
subroutine, public vegetation_module::vegatt(s, par, veg)
References bulkdragcoeff, momeqveg, swvegatt.
Referenced by libxbeach_module::executestep.
subroutine vegetation_module::swvegatt(s, par, veg)
Referenced by vegatt.
subroutine vegetation_module::momeqveg(s, par, veg)
References swvegnonlin, trapz.
Referenced by vegatt.
subroutine vegetation_module::swvegnonlin(s, par, i, j, unl, etaw)
Referenced by momeqveg.
real*8 function vegetation_module::trapz(y, dx)
Referenced by momeqveg.
subroutine vegetation_module::bulkdragcoeff(s, par, ahh, ind, m, i, j, Cdterm, veg)
Referenced by vegatt.